"""Phase 3.2 Executive Reputation Engine

Revision ID: 0b186a3e0525
Revises: 4307c21c7d0b
Create Date: 2026-06-17 07:10:50.381312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b186a3e0525'
down_revision: Union[str, None] = '4307c21c7d0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executive_reputation_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('executive_name', sa.String(length=255), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(length=2), nullable=False),
    sa.Column('sentiment_component', sa.Float(), nullable=False),
    sa.Column('risk_component', sa.Float(), nullable=False),
    sa.Column('narrative_component', sa.Float(), nullable=False),
    sa.Column('trend_component', sa.Float(), nullable=False),
    sa.Column('visibility_component', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('reputation_trend', sa.String(length=20), nullable=False),
    sa.Column('top_positive_narrative', sa.String(length=255), nullable=True),
    sa.Column('top_negative_narrative', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executive_reputation_scores_client_id'), 'executive_reputation_scores', ['client_id'], unique=False)
    op.create_index(op.f('ix_executive_reputation_scores_entity_id'), 'executive_reputation_scores', ['entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_executive_reputation_scores_entity_id'), table_name='executive_reputation_scores')
    op.drop_index(op.f('ix_executive_reputation_scores_client_id'), table_name='executive_reputation_scores')
    op.drop_table('executive_reputation_scores')
    # ### end Alembic commands ###
