"""milestone 3

Revision ID: 241e35833c2a
Revises: 578cf8464839
Create Date: 2026-06-12 05:49:02.134096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '241e35833c2a'
down_revision: Union[str, None] = '578cf8464839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rss_feeds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feed_name', sa.String(length=255), nullable=False),
    sa.Column('feed_url', sa.String(length=1024), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('poll_interval_minutes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_entry_guid', sa.String(length=512), nullable=True),
    sa.Column('last_entry_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('extract_full_article', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feed_url')
    )
    op.create_table('collection_jobs',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('documents_found', sa.Integer(), nullable=True),
    sa.Column('documents_saved', sa.Integer(), nullable=True),
    sa.Column('documents_matched', sa.Integer(), nullable=True),
    sa.Column('documents_deduplicated', sa.Integer(), nullable=True),
    sa.Column('documents_failed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['rss_feeds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.add_column('documents', sa.Column('raw_payload', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'raw_payload')
    op.drop_table('collection_jobs')
    op.drop_table('rss_feeds')
    # ### end Alembic commands ###
