"""drop_raw_payload

Revision ID: 295147d42c18
Revises: db6bdfcef22d
Create Date: 2026-06-12 07:17:15.557219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '295147d42c18'
down_revision: Union[str, None] = 'db6bdfcef22d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'raw_payload')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('raw_payload', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
