"""Phase 2.1 Risk Engine

Revision ID: 3d2e314cd7be
Revises: 994186b679dd
Create Date: 2026-06-17 04:15:16.915302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision: str = '3d2e314cd7be'
down_revision: Union[str, None] = '994186b679dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('risk_factors', app.models.risk.JSONEncodedDict(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_events_client_id'), 'risk_events', ['client_id'], unique=False)
    op.create_index(op.f('ix_risk_events_document_id'), 'risk_events', ['document_id'], unique=False)
    op.create_index(op.f('ix_risk_events_entity_id'), 'risk_events', ['entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_events_entity_id'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_document_id'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_client_id'), table_name='risk_events')
    op.drop_table('risk_events')
    # ### end Alembic commands ###
