"""Phase 3.1 Reputation Engine

Revision ID: 4307c21c7d0b
Revises: 8b3e58085e3c
Create Date: 2026-06-17 06:59:31.979473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4307c21c7d0b'
down_revision: Union[str, None] = '8b3e58085e3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reputation_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(length=2), nullable=False),
    sa.Column('sentiment_component', sa.Float(), nullable=False),
    sa.Column('risk_component', sa.Float(), nullable=False),
    sa.Column('narrative_component', sa.Float(), nullable=False),
    sa.Column('trend_component', sa.Float(), nullable=False),
    sa.Column('source_component', sa.Float(), nullable=False),
    sa.Column('visibility_component', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('reputation_trend', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reputation_scores_client_id'), 'reputation_scores', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reputation_scores_client_id'), table_name='reputation_scores')
    op.drop_table('reputation_scores')
    # ### end Alembic commands ###
