"""milestone 2

Revision ID: 578cf8464839
Revises: 1c221211b7d1
Create Date: 2026-06-12 05:17:26.026927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '578cf8464839'
down_revision: Union[str, None] = '1c221211b7d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matching_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('documents_processed', sa.Integer(), nullable=True),
    sa.Column('matches_found', sa.Integer(), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('keywords_loaded', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('alias_text', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_aliases_alias_text'), 'entity_aliases', ['alias_text'], unique=False)
    op.add_column('document_matches', sa.Column('matched_entity_id', sa.UUID(), nullable=False))
    op.add_column('document_matches', sa.Column('match_type', sa.String(length=50), nullable=True))
    op.add_column('document_matches', sa.Column('match_confidence', sa.Float(), nullable=True))
    op.drop_constraint('document_matches_entity_id_fkey', 'document_matches', type_='foreignkey')
    op.create_foreign_key(None, 'document_matches', 'entities', ['matched_entity_id'], ['id'], ondelete='CASCADE')
    op.drop_column('document_matches', 'entity_id')
    op.add_column('entities', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('entities', sa.Column('domain', sa.String(length=255), nullable=True))
    op.add_column('entities', sa.Column('linkedin_url', sa.String(length=1024), nullable=True))
    op.add_column('entities', sa.Column('ticker_symbol', sa.String(length=20), nullable=True))
    op.add_column('entities', sa.Column('industry', sa.String(length=100), nullable=True))
    op.add_column('entity_keywords', sa.Column('category', sa.String(length=50), nullable=False))
    op.add_column('entity_keywords', sa.Column('priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entity_keywords', 'priority')
    op.drop_column('entity_keywords', 'category')
    op.drop_column('entities', 'industry')
    op.drop_column('entities', 'ticker_symbol')
    op.drop_column('entities', 'linkedin_url')
    op.drop_column('entities', 'domain')
    op.drop_column('entities', 'website')
    op.add_column('document_matches', sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'document_matches', type_='foreignkey')
    op.create_foreign_key('document_matches_entity_id_fkey', 'document_matches', 'entities', ['entity_id'], ['id'], ondelete='CASCADE')
    op.drop_column('document_matches', 'match_confidence')
    op.drop_column('document_matches', 'match_type')
    op.drop_column('document_matches', 'matched_entity_id')
    op.drop_index(op.f('ix_entity_aliases_alias_text'), table_name='entity_aliases')
    op.drop_table('entity_aliases')
    op.drop_table('matching_metrics')
    # ### end Alembic commands ###
