"""milestone 4

Revision ID: 7cf9f709388d
Revises: 241e35833c2a
Create Date: 2026-06-12 06:34:11.108705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cf9f709388d'
down_revision: Union[str, None] = '241e35833c2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_jobs',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('results_found', sa.Integer(), nullable=True),
    sa.Column('results_saved', sa.Integer(), nullable=True),
    sa.Column('results_matched', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('search_source_configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('daily_quota', sa.Integer(), nullable=True),
    sa.Column('rate_limit', sa.Integer(), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('source_priority', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type')
    )
    op.create_table('search_cursors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('keyword_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('cursor_value', sa.String(length=512), nullable=True),
    sa.Column('last_searched_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['entity_keywords.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('entity_keywords', sa.Column('search_frequency_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entity_keywords', 'search_frequency_minutes')
    op.drop_table('search_cursors')
    op.drop_table('search_source_configurations')
    op.drop_table('search_jobs')
    # ### end Alembic commands ###
