"""Phase 2.3 Narrative Engine

Revision ID: 8b3e58085e3c
Revises: 19ffef687ca6
Create Date: 2026-06-17 06:13:41.204510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b3e58085e3c'
down_revision: Union[str, None] = '19ffef687ca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('narratives',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('narrative_name', sa.String(length=255), nullable=False),
    sa.Column('narrative_type', sa.String(length=100), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('trend_strength', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_narratives_client_id'), 'narratives', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_narratives_client_id'), table_name='narratives')
    op.drop_table('narratives')
    # ### end Alembic commands ###
