"""Phase 1E Trends

Revision ID: 994186b679dd
Revises: 4c861087220a
Create Date: 2026-06-16 15:59:59.326992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '994186b679dd'
down_revision: Union[str, None] = '4c861087220a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trend_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('trend_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('baseline_value', sa.Float(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('percentage_change', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trend_events_client_id'), 'trend_events', ['client_id'], unique=False)
    op.create_index(op.f('ix_trend_events_entity_id'), 'trend_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_trend_events_topic_id'), 'trend_events', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trend_events_topic_id'), table_name='trend_events')
    op.drop_index(op.f('ix_trend_events_entity_id'), table_name='trend_events')
    op.drop_index(op.f('ix_trend_events_client_id'), table_name='trend_events')
    op.drop_table('trend_events')
    # ### end Alembic commands ###
