"""add_fk_indexes

Revision ID: db6bdfcef22d
Revises: 7cf9f709388d
Create Date: 2026-06-12 07:15:34.919984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db6bdfcef22d'
down_revision: Union[str, None] = '7cf9f709388d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_collection_jobs_source_id'), 'collection_jobs', ['source_id'], unique=False)
    op.create_index(op.f('ix_document_matches_document_id'), 'document_matches', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_matches_keyword_id'), 'document_matches', ['keyword_id'], unique=False)
    op.create_index(op.f('ix_document_matches_matched_entity_id'), 'document_matches', ['matched_entity_id'], unique=False)
    op.create_index(op.f('ix_documents_source_id'), 'documents', ['source_id'], unique=False)
    op.create_index(op.f('ix_entities_client_id'), 'entities', ['client_id'], unique=False)
    op.create_index(op.f('ix_entity_aliases_entity_id'), 'entity_aliases', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_keywords_entity_id'), 'entity_keywords', ['entity_id'], unique=False)
    op.create_index(op.f('ix_search_cursors_keyword_id'), 'search_cursors', ['keyword_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_cursors_keyword_id'), table_name='search_cursors')
    op.drop_index(op.f('ix_entity_keywords_entity_id'), table_name='entity_keywords')
    op.drop_index(op.f('ix_entity_aliases_entity_id'), table_name='entity_aliases')
    op.drop_index(op.f('ix_entities_client_id'), table_name='entities')
    op.drop_index(op.f('ix_documents_source_id'), table_name='documents')
    op.drop_index(op.f('ix_document_matches_matched_entity_id'), table_name='document_matches')
    op.drop_index(op.f('ix_document_matches_keyword_id'), table_name='document_matches')
    op.drop_index(op.f('ix_document_matches_document_id'), table_name='document_matches')
    op.drop_index(op.f('ix_collection_jobs_source_id'), table_name='collection_jobs')
    # ### end Alembic commands ###
