"""Phase 7: Entity Discovery - Executive and Competitor Candidates

Revision ID: phase_7_entity_discovery
Revises: 4cdcbf89cc1b
Create Date: 2026-07-04 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'phase_7_entity_discovery'
down_revision: Union[str, None] = 'd591a620c92a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create executive_candidates table
    op.create_table('executive_candidates',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('client_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('mention_count', sa.Integer(), nullable=False, server_default='1'),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False, server_default='0.0'),
    sa.Column('source_documents', postgresql.JSONB(), nullable=True, server_default='[]'),
    sa.Column('promoted_to_executive_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promoted_to_executive_id'], ['entities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executive_candidates_client_id'), 'executive_candidates', ['client_id'], unique=False)
    op.create_index(op.f('ix_executive_candidates_name'), 'executive_candidates', ['name'], unique=False)
    
    # Create competitor_candidates table
    op.create_table('competitor_candidates',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('client_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_name', sa.String(length=255), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=False, server_default='1'),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False, server_default='0.0'),
    sa.Column('source_documents', postgresql.JSONB(), nullable=True, server_default='[]'),
    sa.Column('promoted_to_competitor_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promoted_to_competitor_id'], ['entities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_candidates_client_id'), 'competitor_candidates', ['client_id'], unique=False)
    op.create_index(op.f('ix_competitor_candidates_organization_name'), 'competitor_candidates', ['organization_name'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competitor_candidates_organization_name'), table_name='competitor_candidates')
    op.drop_index(op.f('ix_competitor_candidates_client_id'), table_name='competitor_candidates')
    op.drop_table('competitor_candidates')
    
    op.drop_index(op.f('ix_executive_candidates_name'), table_name='executive_candidates')
    op.drop_index(op.f('ix_executive_candidates_client_id'), table_name='executive_candidates')
    op.drop_table('executive_candidates')
    # ### end Alembic commands ###
